# Generated by Django 5.2.1 on 2025-05-16 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0003_remove_cliente_profissao_cliente_complemento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='profissao',
            field=models.CharField(default='Não informado', max_length=100),
        ),
    ]
